apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: b
  labels:
    app: b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: b
  template:
    metadata:
      labels:
        app: b
    spec:
      containers:
      - name: b
        image: b:v0.0.1